plugins:
  - jekyll-relative-links
#  - jekyll-target-blank

relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-slate

title: "CIE100"
description: "Common Intellectual Experience"

url                      : https://BillJr99.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/Ursinus-CIE100-Fall2024" # the subpath of your site, e.g. "/blog"

# Reading Files
include:
  - .htaccess
  - _pages
  - files

